// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLecG-1_7t-s24bsc_OMFievg4wG6SbLk',
    appId: '1:618072093394:web:dcad3e9eb7c9ea6e62330b',
    messagingSenderId: '618072093394',
    projectId: 'fawazchickenres',
    authDomain: 'fawazchickenres.firebaseapp.com',
    storageBucket: 'fawazchickenres.appspot.com',
    measurementId: 'G-9XZPQQ15MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8lpt6DHFuKHEqgIiWOtBmbfeeTzVGyps',
    appId: '1:618072093394:android:924ea87a44b0c03a62330b',
    messagingSenderId: '618072093394',
    projectId: 'fawazchickenres',
    storageBucket: 'fawazchickenres.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuEnq8pM4RuQJul1VXm2rQH012eesR7UM',
    appId: '1:618072093394:ios:4491ae76ea18965962330b',
    messagingSenderId: '618072093394',
    projectId: 'fawazchickenres',
    storageBucket: 'fawazchickenres.appspot.com',
    iosClientId: '618072093394-i0uet6nfgkeit49vvaslk4jkrecsrlin.apps.googleusercontent.com',
    iosBundleId: 'com.example.fawazchickenresturant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuEnq8pM4RuQJul1VXm2rQH012eesR7UM',
    appId: '1:618072093394:ios:f1b1d9c427e90f4e62330b',
    messagingSenderId: '618072093394',
    projectId: 'fawazchickenres',
    storageBucket: 'fawazchickenres.appspot.com',
    iosClientId: '618072093394-gsb2aboa76q38gpdb9020t3g1go2dbqh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fawazchickenresturant.RunnerTests',
  );
}
